;----------------------------------------------------------------------------
;             
;       kernel type definition
;
;----------------------------------------------------------------------------
        			    
  
  
  IF target EQ x86
      
subtitle Hazelnut Kdebug/x86 Version X

kernel_family      = hazelnut
 
kernel_type        = x86   
 
gver = 2

kernel_x2	     = 0
precise_cycles     = 0
random_sampling    = 0      	
random_profiling   = 0   ; = 1 REQUIRES random_sampling = 1

  ENDIF	


 
  


