######################################################################
##                
## Copyright (C) 1999, 2000, 2001,  Karlsruhe University
##                
## File path:     mips/Makefile
##                
## @LICENSE@
##                
## $Id: Makefile,v 1.6 2001/11/22 13:27:53 skoglund Exp $
##                
######################################################################

######################################################################
# the source files...

LIB	= libarch.a
OBJ_SRC = 
LIB_SRC = init.c memory.c mapping.c interrupt.c


######################################################################
# includes
include ../../Makeconf $(wildcard .depend)

######################################################################
# rules

all: $(OBJ) $(LIB)
