/*********************************************************************
 *                
 * Copyright (C) 1999, 2000, 2001,  Karlsruhe University
 *                
 * File path:     version.c
 * Description:   Autogenerated kernel version string.
 *                
 * @LICENSE@
 *                
 * $Id: version.c,v 1.5 2001/11/22 13:04:52 skoglund Exp $
 *                
 ********************************************************************/
const char* kernel_version = "L4Ka/Hazelnut - built on " __DATE__ " " __TIME__
                             " by " __USER__ " using " __GCCVERSION__ "\n";
