;----------------------------------------------------------------------------
;             
;       kernel type definition
;
;----------------------------------------------------------------------------
                    
  
  
  IF target EQ PIII
      
subtitle L4/PIII Version Y
 
kernel_type        = pIII 
 
kernel_char        = '5'

gver = 2

kernel_x2	   = 0	


include adrspac5.inc

  ENDIF	


 
  


